import { ReactComponent as Hotel } from "../../src/Assets/icons/buildings.svg";
import { ReactComponent as Apartement } from "../../src/Assets/icons/house.svg";
import { ReactComponent as Villa } from "../../src/Assets/icons/building-3.svg";
import { ReactComponent as Hostel } from "../../src/Assets/icons/house-2.svg";
import { ReactComponent as Resident } from "../../src/Assets/icons/buildings-2.svg";

import bed from "../Assets/Frame 1707481215.png";

const appData = {
  PaymentMethod: [
    { label: "Paymob", value: "Paymob" },
    { label: "PayPal", value: "PayPal" },
    { label: "Stripe", value: "Stripe" },
    { label: "PayTabs", value: "PayTabs" },
    { label: "Apple Pay", value: "Apple Pay" }
 
  ],
  RoomFacilitie: [

    { value: "Hot tub", label: "Hot tub" },
    { value: "Balcony", label: "Balcony" },
    { value: "Terrace", label: "Terrace" },
    { value: "Air conditioning", label: "Air conditioning" },
    { value: "Safe box", label: "Safe box" },
    { value: "Fireplace", label: "Fireplace" },
    { value: "Bed linens", label: "Bed linens" },
    { value: "Desk", label: "Desk" },
    { value: "Soundproofing", label: "Soundproofing" },
    { value: "Private entrance", label: "Private entrance" },
    { value: "Mosquito net", label: "Mosquito net" },
    { value: "Ironing facilities", label: "Ironing facilities" },
    { value: "Coffee maker", label: "Coffee maker" },
    { value: "Tea/Coffee maker", label: "Tea/Coffee maker" },
    { value: "Iron", label: "Iron" },
    { value: "Heating", label: "Heating" },
    { value: "Flat-screen TV", label: "Flat-screen TV" },
    { value: "Fan", label: "Fan" },
    { value: "Mini bar", label: "Mini bar" },
    { value: "Wake-up service/Alarm clock", label: "Wake-up service/Alarm clock" },
    { value: "Electric kettle", label: "Electric kettle" },
    { value: "Wake-up service", label: "Wake-up service" },
    { value: "Alarm clock", label: "Alarm clock" },
    { value: "Clothes dryer", label: "Clothes dryer" },
    { value: "Wardrobe", label: "Wardrobe" },
    { value: "Entire unit located on ground floor", label: "Entire unit located on ground floor" },
    { value: "Clothes rack", label: "Clothes rack" },
    { value: "Child-safe sockets", label: "Child-safe sockets" },
    { value: "Child safety gates", label: "Child safety gates" },
  ],
  RoomViews: [
    { value: "option1", value: "Mountain View" },
    { value: "option2", value: "City View" },
    { value: "option3", value: "Sea View" },
    { value: "option4", value: "Garden View" },
    { value: "option5", value: "Pool View" },
    { value: "option6", value: "Lake View" },
    { value: "option7", value: "River View" },
    { value: "option8", value: "Landmark View" },
    { value: "option9", value: "Courtyard View" },
    { value: "option10", value: "Ocean View" },
    { value: "option11", value: "Harbor View" },
    { value: "option12", value: "Forest View" },
    { value: "option13", value: "Desert View" },
    { value: "option14", value: "Park View" },
    { value: "option15", value: "Ski Slope View" },
    { value: "option16", value: "Beach View" },
    { value: "option17", value: "Sunset View" },
    { value: "option18", value: "Street View" },
    { value: "option19", value: "Hill View" },
    { value: "option20", value: "Skyline View" }
 ],

  BathroomFacilities: [

    { value: "Shower", label: "Shower" },
    { value: "Bathtub", label: "Bathtub" },
    { value: "Private Toilet", label: "Private Toilet" },
    { value: "Jacuzzi", label: "Jacuzzi" },
    { value: "Hairdryer", label: "Hairdryer" },
    { value: "Towels", label: "Towels" },
    { value: "Shower Gel", label: "Shower Gel" },
    { value: "Shampoo", label: "Shampoo" },
    { value: "Toothbrush", label: "Toothbrush" },
    { value: "Toothpaste", label: "Toothpaste" },
    { value: "Mirror", label: "Mirror" },
    { value: "Bathrobe", label: "Bathrobe" },
    { value: "Slippers", label: "Slippers" },
    { value: "Hot Water", label: "Hot Water" },
    { value: "Bidet", label: "Bidet" },
    { value: "Separate Toilet", label: "Separate Toilet" },
    { value: "Rain Shower", label: "Rain Shower" },
    { value: "Luxury Toiletries", label: "Luxury Toiletries" },
    { value: "Shower Chair", label: "Shower Chair" },
    { value: "Handheld Shower", label: "Handheld Shower" },
    { value: "Water Heater", label: "Water Heater" },
    { value: "Electric Razor", label: "Electric Razor" },
    { value: "Toilet Paper", label: "Toilet Paper" },
    { value: "Face Towel", label: "Face Towel" },
    { value: "Bath Towel", label: "Bath Towel" },
    { value: "Shower Cap", label: "Shower Cap" },
    { value: "Body Lotion", label: "Body Lotion" },
    { value: "Cotton Buds", label: "Cotton Buds" },
    { value: "Hair Straightener", label: "Hair Straightener" },
    { value: "Shaving Kit", label: "Shaving Kit" },
    { value: "Waterproof Shower Curtain", label: "Waterproof Shower Curtain" },
    { value: "Hand Wash", label: "Hand Wash" },
    { value: "Anti-slip Mat", label: "Anti-slip Mat" },
    { value: "Toilet Brush", label: "Toilet Brush" },
    { value: "Bath Mat", label: "Bath Mat" },
    { value: "Deodorant", label: "Deodorant" },
    { value: "Plunger", label: "Plunger" },
    { value: "Linen", label: "Linen" },
    { value: "Soap Dispenser", label: "Soap Dispenser" },
    { value: "Towel Rack", label: "Towel Rack" },
    { value: "Laundry Basket", label: "Laundry Basket" },
    { value: "Sink", label: "Sink" },
    { value: "Mirror with Lighting", label: "Mirror with Lighting" },
    { value: "Shower Bench", label: "Shower Bench" }
    
    
  ],
  RoomMain: [
    { value: "option1", value: "Dishwasher" },
    { value: "option2", value: "Wardrobe" },
    { value: "option3", value: "Microwave" },
  ],
  bedsData: [
    { img: bed, title: "Single Bed", description: "90 - 130 cm wide" },
    { img: bed, title: "Double Bed", description: "131 - 180 cm wide" },
    { img: bed, title: "Queen Bed", description: "150 - 200 cm wide" },
    { img: bed, title: "King Bed", description: "180 - 220 cm wide" },
    { img: bed, title: "Sofa Bed", description: "Varies in size" },
    { img: bed, title: "Bunk Bed", description: "Twin over Twin" },
    { img: bed, title: "Futon Bed", description: "Multi-functional sofa bed" },
    { img: bed, title: "Day Bed", description: "Can be used as a sofa" },
    { img: bed, title: "Murphy Bed", description: "Foldable into a wall" },
  ],
  RoomType: [
    { value: "Single Room", label: "Single Room" },
    { value: "Double Room", label: "Double Room" },
    { value: "Triple Room", label: "Triple Room" },
    { value: "Quad Room", label: "Quad Room" },
    { value: "Suit Room", label: "Suit Room" },
    { value: "Junior Suite Room", label: "Junior Suite Room" },
    { value: "Executive Suite Room", label: "Executive Suite Room" }
  ],
  stepsData: [
    {
      stepNumber: 1,
      title: "Complete Your Profile",
      description:
        "The basics. Add your property name, address, facilities and more.",
    },
    {
      stepNumber: 2,
      title: "Hotel Details",
      description:
        "The basics. Add your property name, address, facilities and more.",
    },
    {
      stepNumber: 3,
      title: "Hotel Images",
      description:
        "The basics. Add your property name, address, facilities and more.",
    },
    {
      stepNumber: 4,
      title: "Room Details",
      description:
        "The basics. Add your property name, address, facilities and more.",
    },
    {
      stepNumber: 5,
      title: "Room Images",
      description:
        "The basics. Add your property name, address, facilities and more.",
    },
  ],
  times: [
    { label: "1.00", value: "1.00" },
    { label: "12.00", value: "12.00" },
    { label: "2.00", value: "2.00" },
    { label: "3.00", value: "3.00" },
    { label: "4.00", value: "4.00" },
    { label: "5.00", value: "5.00" },
    { label: "6.00", value: "6.00" },
    { label: "7.00", value: "7.00" },
    { label: "8.00", value: "8.00" },
    { label: "9.00", value: "9.00" },
    { label: "10.00", value: "10.00" },
    { label: "11.00", value: "11.00" },
  ],
  petsPolicy: [
    { value: "option2", policy: "Pets are not allowed." },
    { value: "option3", policy: "Pets are allowed at no additional cost." },
    { value: "option4", policy: "Pets allowed at an additional cost." },
  ],
  smokingPolicy: [
    { value: "option2", policy: "No smoking allowed." },
   
    { value: "option4", policy: "Smoking is allowed." },
  ],
  facilities: [
    { value: "option1", facilitie: "Free WiFi" },
    { value: "option2", facilitie: "Swimming Pool" },
    { value: "option3", facilitie: "Indoor Pool" },
    { value: "option4", facilitie: "Outdoor Pool" },
    { value: "option5", facilitie: "Infinity Pool" },
    { value: "option6", facilitie: "Heated Pool" },
    { value: "option7", facilitie: "Fitness Center" },
    { value: "option8", facilitie: "Spa" },
    { value: "option9", facilitie: "Massage Services" },
    { value: "option10", facilitie: "Beauty Salon" },
    { value: "option11", facilitie: "Hairdresser" },
    { value: "option12", facilitie: "Restaurant" },
    { value: "option13", facilitie: "Bar" },
    { value: "option14", facilitie: "Lounge Area" },
    { value: "option15", facilitie: "Rooftop Bar" },
    { value: "option16", facilitie: "Café" },
    { value: "option17", facilitie: "Room Service" },
    { value: "option18", facilitie: "24-Hour Front Desk" },
    { value: "option19", facilitie: "Airport Shuttle" },
    { value: "option20", facilitie: "Parking" },
    { value: "option21", facilitie: "Secure Parking" },
    { value: "option22", facilitie: "Valet Parking" },
    { value: "option23", facilitie: "Electric Vehicle Charging" },
    { value: "option24", facilitie: "Air Conditioning" },
    { value: "option25", facilitie: "Non-smoking Rooms" },
    { value: "option26", facilitie: "Business Center" },
    { value: "option27", facilitie: "Conference Facilities" },
    { value: "option28", facilitie: "Meeting Rooms" },
    { value: "option29", facilitie: "Business Lounge" },
    { value: "option30", facilitie: "High-Speed Internet" },
  ],
  languages: [
    { value: "option1", lang: "Arabic" },
    { value: "option2", lang: "English" },
    { value: "option3", lang: "German" },
    { value: "option4", lang: "Mandarin" },
    { value: "option5", lang: "Portugals" },
  ],
  ChoiseHotel: [
    {
      title: "Hotel",
      img: Hotel,
      desc: "Accommodation for travellers often offering restaurants, meeting rooms and other guest services",
    },
    {
      title: "Apartment",
      img: Apartement,
      desc: "Make Tour, sit planning to attraction and more..",
    },
    {
      title: "Villa",
      img: Villa,
      desc: "Make Tour, sit planning to attraction and more..",
    },
    {
      title: "Hostel",
      img: Hostel,
      desc: "Make Tour, sit planning to attraction and more..",
    },
    {
      title: "Resident",
      img: Resident,
      desc: "Make Tour, sit planning to attraction and more..",
    },
  ],
  fileList: [
    { name: "Business Registration Certificate", required: false },
    { name: "Hotel License", required: false },
    { name: "Tax Registration Certificate (TIN)", required: false },
  ],
};

export default appData;
